language: node_js
sudo: false
node_js:
- '5.6'
services:
- postgresql
before_script:
- npm install -g gulp
- npm install -g knex
- psql -c 'create database sheltered_test;' -U postgres
- npm run migrate
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: lnGiFJbZeEVv0AJHPRFddEmmPmk9QrCsSzqeYJ/mfr6+2ZXpu4h7/Zj5r7DBjT5WnanJ27L3SL4k3RGZcNN3sA6zGVyjY6l48Yr+P8oSaR8rTGlEx4H+WCN4RAJrI5k5k1E9BnCZxsPRt0136ZDk99Bx8zGfHz4TjlHdTDnET1jnBm+wODju/wUeadIJg7gDGw9355hrYyqsOWZl13U6DEmd81UymZGW0MwGBehH0lFBf9Id+g45SmanRE/DW9l+hyhHp5HMk72UoIHt0/A17OVBcxXN0CE6Vq6v1/20meDzwDFziV3ZqRhPYB37hh1Z039ZF5lwNEfMdVmkHRbKHjp0iEpA9jTSIOqrvTnjbbavgSLg9xWbpXV7+Y8dKgqTJsVSoyOzkNQ1yi2xfnbAP7jS3clEvApAYzcOF/TKvLXql5AKgkjrSrwN6v6aL0LqJnPc9W/Uuog+VVoZFADCD5nkgNjWTA4du7he9A3G4THjFJIE10ntbRqlmi02HSQW6cQxiVzdgx6Ho/BUrpNYB86eCT3F++WpYED7mOZU+MLQN/vhTlBntrBwYqZSjzS3FMQUEH5eWCb3nORONi0nRmLmCNJNG9yVe7JTfluRC/XTpYU00TLKJTNuqU+p0utbu91/Q7GeNg/0rSnxjtmb/910aN+VZlqJUJRV1Q3oHe4=
  on:
    branch: master
  after_deploy:
  - npm seed
  - gulp
  before_deploy:
  - echo 'pushing to heroku!'
 
